apiVersion: v1
kind: Service
metadata:
  name: node-deployment-service
spec:
  selector:
      app: node-app
      tier: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer