
# ==================================================================================================================================================================
#   Kubeconfig file
# ==================================================================================================================================================================
apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://example.com:6443
    certificate-authority-data: <certificate-authority-data>
users:
- name: my-user
  user:
    client-certificate-data: <client-certificate-data>
    client-key-data: <client-key-data>
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
    namespace: my-namespace # default
current-context: my-context


# ==================================================================================================================================================================
#   Service
# ==================================================================================================================================================================
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080


# ==================================================================================================================================================================
#   Deployment
# ==================================================================================================================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: my-app-image:latest


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================



# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================



# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================



# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================



# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================



# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================



# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================


# ==================================================================================================================================================================
#   
# ==================================================================================================================================================================