apiVersion: v1
kind: Service
metadata:
  name: task-api-deployment-service
spec:
  selector:
      app: task-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer