apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  labels:
    app: user---api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api-app
          image: princewillopah/max_k8s_networking_user:v1
          imagePullPolicy: Always
          env:
            - name: AUTH_ADDRESS
              value: "auth-api-deployment-service.default"

