apiVersion: v1
kind: Service
metadata:
  name: store-load-balancer-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    component: store

