apiVersion: v1
kind: Pod
metadata:
   name: node-pod
   labels:
      app: node-ws
spec:
   containers:
   - name: node-container
     image: koperate10/mynodeapp:latest
     ports:
       - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
   name: mygame-svc
spec:
   selector:
      app: node-ws
   ports:
   - protocol: TCP
     port: 80
     targetPort: 3000
   type: LoadBalancer