version: "3.8"

services:
  app:
    container_name: node-hello-app-dev
    image: node-hello-app-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 5000:5000